version: "3.9"
services:

    mysql:
      image: mysql:8.0
      environment:
        - MYSQL_ROOT_PASSWORD=abc123
      ports: 
        - "3306:3306"




    app:
      # tty: true
    
      build:
      context: .
      dockerfile: Dockerfile_tests
      depends_on:
       - mysql
      condition: service_healthy    

    coverage:
     #tty: true
     
     build:
       context: .
       dockerfile: Dockerfile_tests
     depends_on:
        - mysql
     condition: service_healthy
     entrypoint: bash -c "python3 -m coverage run -m unittest && python3 -m coverage html"
     volumes:
       - ./coverage:/workdir/htmlcov
