name: Build

on: 
  push:
    branches: [main]

# env:
#   REGISTRY: ghcr.io
#   IMAGE_NAME: ${{ github.repository }}

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      # packages: write
    steps:
    - uses: actions/checkout@v3

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: false
        tags: mysql-conn:latest
